- name: Coping Redis Repo
  ansible.builtin.copy:
    src: redis.repo
    dest:  /etc/yum.repos.d/redis.repo

- name: Install Redis
  ansible.builtin.package:
    name: redis-6.2.9
    state: present

- name: Set-Hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}

    
