- name: Coping MongoDB Repo
  ansible.builtin.copy:     #copies the files from the files directory
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Updating MongoDB Config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting MongoDB service
  ansible.builtin.service:
    name: mongod
    state: started

- name: Download and extracting
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/mongodb/archive/main.zip"
    dest: /tmp
    remote_src: yes       #remore_src:yes tells that the source to be downloaded/copied is not locally available

- name: Load Catalogue Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    indempotent: yes
    