- name: Demo on shell module
  hosts: all
  tasks:
    - name: Execute shell command 
      ansible.builtin.shell: uptime
      register: OUT

    - name: printing output variable
      ansible.builtin.debug:
        msg: "{{OUT}}"