- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Download and extracting
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/frontend/archive/main.zip"
    dest: /tmp
    remote_src: yes       #remore_src:yes tells that the source to be downloaded/copied is not locally available

- name: Clearing old HTML Content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Coping the Frontend Content to Nginx path 
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest:  /usr/share/nginx/html/
    remote_src: yes   #since the source is on a remore machine, ensure you mention remote_src as yes

- name: Coping Nginx Config
  ansible.builtin.copy:     #copies the files from the files directory
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart nginx service

- name: Starting frontend service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

