- name: Configuring Nodejs Repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install Nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Creating the Application User Account
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop service account

- name: Download and extracting the Component
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes       #remore_src:yes tells that the source to be downloaded/copied is not locally available

- name: Copy file tovthe roboshopp home directory
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    
