- name: Configuring Nodejs Repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install Nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Calling Roboshop User
  include_role:
    name: common
    tasks_from: create-user

- name: Download and extracting the component
  include_role:
    name: common
    tasks_from: download

- name: Install node.js packages
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: configuring service
  include_role:
    name: common
    tasks_from: config-svc


- name: Set-Hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}
